name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Specify your desired .NET version

      # Install lftp
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp          

      # Restore, build, and publish the .NET application
      - name: Restore, build, and publish
        run: |
          dotnet restore
          dotnet build $GITHUB_WORKSPACE/ResumeData/ResumeData.csproj --configuration Release
          dotnet publish $GITHUB_WORKSPACE/ResumeData/ResumeData.csproj --configuration Release -o $GITHUB_WORKSPACE/publish

      - name: Database Restore, build, and publish
        run: |
          dotnet restore
          dotnet build $GITHUB_WORKSPACE/Database/Database.csproj --configuration Release
          dotnet publish $GITHUB_WORKSPACE/Database/Database.csproj --configuration Release -o $GITHUB_WORKSPACE/publishDb

      - name: Database Restore, build, and publish
        env:
          PAGINATION_DBCONN: ${{ secrets.PAGINATION_DBCONN }}
        run: |
            $GITHUB_WORKSPACE/publishDb/DatabaseDeploy.exe

      - name: Update DatabaseConnection
        env:
          PAGINATION_DBCONN: ${{ secrets.PAGINATION_DBCONN }}
        run: |
          jq '.ConnectionStrings.PaginatedDataConnection = env.PAGINATION_DBCONN' $GITHUB_WORKSPACE/publish/appsettings.json > $GITHUB_WORKSPACE/publisht $GITHUB_WORKSPACE/publish/temp.json
          mv $GITHUB_WORKSPACE/publish/temp.json $GITHUB_WORKSPACE/publish/appsettings.json  
  
      # Upload build to remote server using FTPS and after this clobber the appsettings.json file
      - name: Deploy to remote server
        env:
          # The user should be scope limited to the root of the site (e.g. sub folder)
          FTPS_USER: ${{ secrets.FTPS_USER }}
          FTPS_PASS: ${{ secrets.FTPS_PASS }}
          FTPS_HOST: ${{ secrets.FTPS_HOST }}
        run: |
          lftp -u $FTPS_USER,$FTPS_PASS -e "set ssl:verify-certificate no; mirror -R publish / && quit" $FTPS_HOST
          rm $GITHUB_WORKSPACE/publish/appsettings.json
